language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  - "iojs-v1.1"
  - "iojs-v1.0"
before_install:
  - "npm install -g npm@2.1.18"
script:
  - "npm run test && npm run integration"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
    - node_js: "0.9"
    - node_js: "iojs-v1.1"
    - node_js: "iojs-v1.0"
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
